PRAGMA foreign_keys = on;

CREATE TABLE IF NOT EXISTS SEARCHES (
    Keyword TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS SUBTITLES (
    Name TEXT NOT NULL UNIQUE,
    Keyword TEXT NOT NULL,
    FOREIGN KEY (Keyword) REFERENCES SEARCHES (Keyword)       
);